apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cluster-health-analyzer
  name: cluster-health-mcp-server
  namespace: openshift-cluster-health-analyzer
spec:
  ports:
  - name: mcp
    port: 8085
    targetPort: mcp
  selector:
    app.kubernetes.io/name: cluster-health-analyzer
